import { combineReducers } from 'redux';
import { routerReducer } from 'react-router-redux';
import {
	Topic,
	CategoryValue,
	CurrentCats,
	RemovedCat,
	EditCatValue,
	EditCat,
	NewEditValue,
	NewValueCats,
	OldValueCats,
	Edited
} from './category';
import {
	Locations,
	LocationName,
	LocationAddress,
	LocationCoordinates,
	LocationCoordinates2,
	LocationCategory,
	RemovedLocation,
	NewLocationName,
	NewLocationAddress,
	NewLocationCoordinates,
	NewLocationCoordinates2,
	NewLocationCategory,
	OldLocationValue,
	AlertAddIncomplete,
	CategorySorted,
	ChoseACatLoc,
	Properties,
	NewLoc,
	Latitude,
	Longitude,
	ShowingMap
}
from './location';

export const rootReducer = combineReducers({
	Topic,
	CategoryValue,
	CurrentCats,
	RemovedCat,
	EditCatValue,
	EditCat,
	NewEditValue,
	NewValueCats,
	OldValueCats,
	Edited,
	Locations,
	LocationName,
	LocationAddress,
	LocationCoordinates,
	LocationCoordinates2,
	LocationCategory,
	RemovedLocation,
	NewLocationName,
	NewLocationAddress,
	NewLocationCoordinates,
	NewLocationCoordinates2,
	NewLocationCategory,
	OldLocationValue,
	AlertAddIncomplete,
	CategorySorted,
	ChoseACatLoc,
	Properties,
	NewLoc,
	Latitude,
	Longitude,
	ShowingMap,
	routing: routerReducer
});